Update FIMSMGR.FABBKTP
Set FABBKTP_RECON_IND = ''
Where FABBKTP_CHECK_DEPOSIT_CODE in ();

select FABBKTP_RECON_IND from FIMSMGR.FABBKTP Where FABBKTP_CHECK_DEPOSIT_CODE in ();

Update FIMSMGR.FABCHKS
Set FABCHKS_RECON_IND = ''
Where FABCHKS_CHECK_NUM in ();

select FABCHKS_RECON_IND from FIMSMGR.FABCHKS Where FABCHKS_CHECK_NUM in ();
